<?php

namespace Drutiny\ProfileSource;

use Drutiny\LanguageManager;
use Drutiny\Profile;

/**
 * Provide policies for Drutiny to use.
 */
interface ProfileSourceInterface
{
    /**
     * Return a list of policy definitions.
     *
     * Each definition should contain keys for name and description.
     * The definition is passed to the ::load() function to load a Policy object.
     *
     * @param \Drutiny\LanguageManager $languageManager
     */
    public function getList(LanguageManager $languageManager):array;

    /**
     * Load a Drutiny\Policy object.
     *
     * @param array $definition
     *  A definition array generated by PolicySourceInterface::getList().
     */
    public function load(array $definition):Profile;

    /**
     * Clear the cache and run getList() to refresh the profile list.
     */
    public function refresh(LanguageManager $languageManager): array;
}
