<?php

namespace Drutiny\PolicySource;

use Drutiny\LanguageManager;
use Drutiny\Policy;
use Generator;

/**
 * Provide policies for Drutiny to use.
 */
interface PolicySourceInterface
{
  /**
   * Return a list of policy definitions.
   *
   * Each definition should contain keys for name and description.
   * The definition is passed to the ::load() function to load a Policy object.
   *
   * @param \Drutiny\LanguageManager $languageManager
   */
    public function getList(LanguageManager $languageManager):array;

  /**
   * Load a Drutiny\Policy object.
   *
   * @param array $definition
   *  A definition array generated by PolicySourceInterface::getList().
   */
    public function load(array $definition):Policy;

    /**
     * Clear the cache and run getList() to refresh the policy list.
     */
    public function refresh(LanguageManager $languageManager): Generator;
}
