<?php

namespace Drutiny;

use Generator;

/**
 * A source to load policies or profiles in from.
 */
interface SourceInterface
{
    /**
     * Return a list of definitions.
     *
     * Each definition should contain keys for name and description.
     * The definition is passed to the ::load() function to load an object.
     *
     * @param \Drutiny\LanguageManager $languageManager
     */
    public function getList(LanguageManager $languageManager):array;

    /**
     * Load an object.
     *
     * @param array $definition
     *  A definition array generated by \Drutiny\SourceInterface::getList().
     */
    public function load(array $definition);

    /**
     * Clear the cache and run getList() to refresh the policy list.
     */
    public function refresh(LanguageManager $languageManager): Generator;
}